# CMake generated Testfile for 
# Source directory: /phenix_ws/mujoco_mpc/mjpc/test/direct
# Build directory: /phenix_ws/mujoco_mpc/mjpc/test/direct
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ForceCost.Particle "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_force_test" "--gtest_filter=ForceCost.Particle")
set_tests_properties(ForceCost.Particle PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;15;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(ForceCost.Box "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_force_test" "--gtest_filter=ForceCost.Box")
set_tests_properties(ForceCost.Box PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;15;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(ForceCost.ParticleDamped "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_force_test" "--gtest_filter=ForceCost.ParticleDamped")
set_tests_properties(ForceCost.ParticleDamped PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;15;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(DirectParameter.ParticleFramePos "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_parameter_test" "--gtest_filter=DirectParameter.ParticleFramePos")
set_tests_properties(DirectParameter.ParticleFramePos PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;18;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(DirectOptimize.Particle2D "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_optimize_test" "--gtest_filter=DirectOptimize.Particle2D")
set_tests_properties(DirectOptimize.Particle2D PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;21;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(DirectOptimize.Box3D "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_optimize_test" "--gtest_filter=DirectOptimize.Box3D")
set_tests_properties(DirectOptimize.Box3D PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;21;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(SensorCost.Particle "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_sensor_test" "--gtest_filter=SensorCost.Particle")
set_tests_properties(SensorCost.Particle PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;24;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(SensorCost.Box "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_sensor_test" "--gtest_filter=SensorCost.Box")
set_tests_properties(SensorCost.Box PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;24;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(DirectTrajectory.Test "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_trajectory_test" "--gtest_filter=DirectTrajectory.Test")
set_tests_properties(DirectTrajectory.Test PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;27;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(FiniteDifferenceVelocityAcceleration.Particle1D "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_utilities_test" "--gtest_filter=FiniteDifferenceVelocityAcceleration.Particle1D")
set_tests_properties(FiniteDifferenceVelocityAcceleration.Particle1D PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;30;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(FiniteDifferenceVelocityAcceleration.Box3D "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/direct_utilities_test" "--gtest_filter=FiniteDifferenceVelocityAcceleration.Box3D")
set_tests_properties(FiniteDifferenceVelocityAcceleration.Box3D PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/phenix_ws/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.28/Modules/GoogleTest.cmake;402;add_test;/phenix_ws/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;30;test;/phenix_ws/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
